// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpHalo.Foundation.Infrastructure.Persistence;

#nullable disable

namespace OpHalo.Foundation.Infrastructure.Migrations
{
    [DbContext(typeof(OpHaloDbContext))]
    [Migration("20260710095627_AddServiceLocationToKeepRequest")]
    partial class AddServiceLocationToKeepRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<Guid?>("PrimaryOwnerAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_owner_account_user_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("PrimaryOwnerAccountUserId")
                        .HasDatabaseName("ix_accounts_primary_owner_account_user_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountAuthCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BusinessNameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name_snapshot");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("DeliveryEmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("delivery_email_snapshot");

                    b.Property<int?>("EntryContext")
                        .HasColumnType("integer")
                        .HasColumnName("entry_context");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at_utc");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("NameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<Guid?>("TargetAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_user_id");

                    b.Property<string>("TimeZoneSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_account_auth_codes");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_auth_codes_account_id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_auth_codes_code_hash");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_account_auth_codes_expires_at_utc");

                    b.HasIndex("TargetAccountUserId")
                        .HasDatabaseName("ix_account_auth_codes_target_account_user_id");

                    b.HasIndex("DeliveryEmailSnapshot", "EntryContext")
                        .HasDatabaseName("ix_account_auth_codes_delivery_email_entry_context");

                    b.ToTable("account_auth_codes", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountEntitlements", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<string>("CommercialState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("commercial_state");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<int>("MaxUserSeats")
                        .HasColumnType("integer")
                        .HasColumnName("max_user_seats");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("OperatingMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operating_mode");

                    b.Property<DateTime?>("PastDueGraceEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("past_due_grace_ends_at_utc");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<DateTime?>("TrialEndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_account_entitlements");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_entitlements_account_id");

                    b.ToTable("account_entitlements", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_user_id");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_token_hash");

                    b.HasKey("Id")
                        .HasName("pk_account_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_sessions_account_id");

                    b.HasIndex("AccountUserId")
                        .HasDatabaseName("ix_account_sessions_account_user_id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_account_sessions_expires_at_utc");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_sessions_token_hash");

                    b.ToTable("account_sessions", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("InviteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invite_expires_at_utc");

                    b.Property<string>("InviteTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite_token_hash");

                    b.Property<string>("MembershipStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("membership_status");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_users");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_account_users_account_id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_users_account_id");

                    b.HasIndex("InviteTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_account_users_invite_token_hash")
                        .HasFilter("invite_token_hash IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_users_user_id");

                    b.HasIndex("AccountId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_account_users_account_email")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("AccountId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_users_account_user")
                        .HasFilter("user_id IS NOT NULL AND deleted_at_utc IS NULL");

                    b.ToTable("account_users", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountUserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_user_id");

                    b.Property<Guid>("AppInstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_installation_id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("LastDeliveryFailureAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivery_failure_at_utc");

                    b.Property<string>("LastDeliveryFailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_delivery_failure_reason");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("push_token");

                    b.Property<string>("PushTokenFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("push_token_fingerprint");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TokenLastFour")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("token_last_four");

                    b.HasKey("Id")
                        .HasName("pk_account_user_devices");

                    b.HasIndex("PushTokenFingerprint")
                        .HasDatabaseName("ix_account_user_devices_fingerprint_active")
                        .HasFilter("status = 'Active' AND push_token_fingerprint IS NOT NULL");

                    b.HasIndex("AccountId", "AccountUserId")
                        .HasDatabaseName("ix_account_user_devices_account_user");

                    b.HasIndex("AccountUserId", "AppInstallationId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_user_devices_user_install");

                    b.ToTable("account_user_devices", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.MobileHandoffCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_user_id");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_mobile_handoff_codes");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_mobile_handoff_codes_account_id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_mobile_handoff_codes_code_hash");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_mobile_handoff_codes_expires_at_utc");

                    b.ToTable("mobile_handoff_codes", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at_utc");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepBusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerFacingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("customer_facing_email");

                    b.Property<string>("CustomerFacingPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_facing_phone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_business_profiles");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_business_profiles_account_id");

                    b.ToTable("keep_business_profiles", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CanonicalPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("canonical_phone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primary_phone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_customers");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_keep_customers_account_id");

                    b.HasIndex("AccountId", "CanonicalPhone")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_customers_account_canonical_phone");

                    b.ToTable("keep_customers", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepProductOpsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_product_ops_events");

                    b.HasIndex("AccountId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_product_ops_events_account_event_type");

                    b.ToTable("keep_product_ops_events", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepPublicIntakeLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("PublicSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("public_slug");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_public_intake_links");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_public_intake_links_account_active")
                        .HasFilter("revoked_at_utc IS NULL AND deleted_at_utc IS NULL");

                    b.HasIndex("PublicSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_public_intake_links_active_slug")
                        .HasFilter("revoked_at_utc IS NULL AND deleted_at_utc IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_public_intake_links_active_token_hash")
                        .HasFilter("revoked_at_utc IS NULL AND deleted_at_utc IS NULL");

                    b.ToTable("keep_public_intake_links", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepPublicIntakeSlugAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<Guid>("IntakeLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("intake_link_id");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at_utc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_public_intake_slug_aliases");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_keep_public_intake_slug_aliases_account_id");

                    b.HasIndex("IntakeLinkId")
                        .HasDatabaseName("ix_keep_public_intake_slug_aliases_intake_link_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_public_intake_slug_aliases_active_slug")
                        .HasFilter("retired_at_utc IS NULL AND deleted_at_utc IS NULL");

                    b.ToTable("keep_public_intake_slug_aliases", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AttentionClearReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("attention_clear_reason");

                    b.Property<DateTime?>("AttentionClearedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attention_cleared_at_utc");

                    b.Property<Guid?>("AttentionClearedByAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("attention_cleared_by_account_user_id");

                    b.Property<string>("AttentionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attention_level");

                    b.Property<string>("AttentionReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("attention_reason");

                    b.Property<DateTime?>("AttentionSinceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attention_since_utc");

                    b.Property<Guid>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrentStatusText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("current_status_text");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<DateTime?>("CustomerPageLastViewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("customer_page_last_viewed_at_utc");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_phone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FeedbackComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("feedback_comment");

                    b.Property<string>("FeedbackReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("feedback_review_note");

                    b.Property<DateTime?>("FeedbackReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_reviewed_at_utc");

                    b.Property<Guid?>("FeedbackReviewedByAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_reviewed_by_account_user_id");

                    b.Property<DateTime?>("FeedbackSubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_submitted_at_utc");

                    b.Property<bool?>("FeedbackWasResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("feedback_was_resolved");

                    b.Property<DateTime?>("FirstRespondedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_responded_at_utc");

                    b.Property<Guid?>("FirstResponderAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_responder_account_user_id");

                    b.Property<DateTime?>("FirstResponseDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_due_at_utc");

                    b.Property<Guid?>("FirstResponseEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_response_event_id");

                    b.Property<string>("FollowUpNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("follow_up_note");

                    b.Property<DateOnly?>("FollowUpOnDate")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_on_date");

                    b.Property<string>("FollowUpReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("follow_up_reason");

                    b.Property<Guid>("KeepCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("keep_customer_id");

                    b.Property<DateTime?>("LastBusinessActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_business_activity_at");

                    b.Property<DateTime?>("LastCustomerActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_customer_activity_at");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<bool>("NeedsShare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("needs_share");

                    b.Property<DateTime?>("NextAttentionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attention_at_utc");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origin");

                    b.Property<string>("PageToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("page_token");

                    b.Property<DateOnly?>("PlannedForDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_for_date");

                    b.Property<string>("PriorityBand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority_band");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference_code");

                    b.Property<string>("ServiceAddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_address_line1");

                    b.Property<string>("ServiceAddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_address_line2");

                    b.Property<string>("ServiceCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_city");

                    b.Property<string>("ServiceState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("service_state");

                    b.Property<string>("ServiceZip")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("service_zip");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TerminatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terminated_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WaitingDirection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("waiting_direction");

                    b.HasKey("Id")
                        .HasName("pk_keep_requests");

                    b.HasAlternateKey("AccountId", "Id")
                        .HasName("ak_keep_requests_account_id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_keep_requests_account_id");

                    b.HasIndex("PageToken")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_requests_page_token");

                    b.HasIndex("AccountId", "AttentionClearedByAccountUserId")
                        .HasDatabaseName("ix_keep_requests_account_id_attention_cleared_by_account_user_");

                    b.HasIndex("AccountId", "FeedbackReviewedByAccountUserId")
                        .HasDatabaseName("ix_keep_requests_account_id_feedback_reviewed_by_account_user_");

                    b.HasIndex("AccountId", "FirstResponderAccountUserId")
                        .HasDatabaseName("ix_keep_requests_account_id_first_responder_account_user_id");

                    b.HasIndex("AccountId", "KeepCustomerId")
                        .HasDatabaseName("ix_keep_requests_account_id_keep_customer_id");

                    b.HasIndex("AccountId", "ReferenceCode")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_requests_account_reference_code");

                    b.HasIndex("AccountId", "AttentionLevel", "AttentionSinceUtc")
                        .HasDatabaseName("ix_keep_requests_account_attention");

                    b.HasIndex("AccountId", "Id", "FirstResponseEventId")
                        .HasDatabaseName("ix_keep_requests_account_id_id_first_response_event_id");

                    b.ToTable("keep_requests", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepRequestEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("ActorAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_account_user_id");

                    b.Property<string>("ActorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_display_name");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_type");

                    b.Property<string>("CommunicationChannel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("communication_channel");

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("ExternalContactClearedAttention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("external_contact_cleared_attention");

                    b.Property<string>("ExternalContactDirection")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_contact_direction");

                    b.Property<string>("ExternalContactOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_contact_outcome");

                    b.Property<bool?>("ExternalContactRequiresFollowUp")
                        .HasColumnType("boolean")
                        .HasColumnName("external_contact_requires_follow_up");

                    b.Property<bool>("ExternalContactSetFirstResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("external_contact_set_first_response");

                    b.Property<DateOnly?>("FollowUpOnDate")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_on_date");

                    b.Property<string>("FollowUpOnReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("follow_up_on_reason");

                    b.Property<string>("MessageIntent")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("message_intent");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ParticipationAction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("participation_action");

                    b.Property<string>("ParticipationInternalNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("participation_internal_note");

                    b.Property<Guid?>("ParticipationNotificationIntendedRecipientAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("participation_notification_intended_recipient_account_user_id");

                    b.Property<string>("ParticipationNotificationIntentKind")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("participation_notification_intent_kind");

                    b.Property<Guid?>("ParticipationPreviousResponsibleAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("participation_previous_responsible_account_user_id");

                    b.Property<Guid?>("ParticipationTargetAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("participation_target_account_user_id");

                    b.Property<string>("ParticipationTargetDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("participation_target_display_name");

                    b.Property<DateOnly?>("PlannedForDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_for_date");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("StatusAfter")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_after");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_keep_request_events");

                    b.HasAlternateKey("AccountId", "RequestId", "Id")
                        .HasName("ak_keep_request_events_account_request_event");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_keep_request_events_account_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_keep_request_events_request_id");

                    b.HasIndex("AccountId", "ActorAccountUserId")
                        .HasDatabaseName("ix_keep_request_events_account_id_actor_account_user_id");

                    b.HasIndex("AccountId", "ParticipationNotificationIntendedRecipientAccountUserId")
                        .HasDatabaseName("ix_keep_request_events_account_id_participation_notification_i");

                    b.HasIndex("AccountId", "ParticipationPreviousResponsibleAccountUserId")
                        .HasDatabaseName("ix_keep_request_events_account_id_participation_previous_respo");

                    b.HasIndex("AccountId", "ParticipationTargetAccountUserId")
                        .HasDatabaseName("ix_keep_request_events_account_id_participation_target_account");

                    b.ToTable("keep_request_events", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepRequestParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("AccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_user_id");

                    b.Property<DateTime>("AttachedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTime?>("DetachedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detached_at_utc");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notifications_enabled");

                    b.Property<string>("ParticipationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("participation_type");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_request_participants");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_request_participants_request_id")
                        .HasFilter("participation_type = 'Responsible' AND detached_at_utc IS NULL");

                    b.HasIndex("AccountId", "AccountUserId")
                        .HasDatabaseName("ix_keep_request_participants_account_user");

                    b.HasIndex("AccountId", "RequestId")
                        .HasDatabaseName("ix_keep_request_participants_account_id_request_id");

                    b.HasIndex("RequestId", "AccountUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_request_participants_request_user");

                    b.ToTable("keep_request_participants", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepResponsePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<bool?>("BusinessHoursOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("business_hours_only");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<int>("FirstResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("first_response_target_minutes");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<int>("PriorityResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("priority_response_target_minutes");

                    b.Property<int>("StandardResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("standard_response_target_minutes");

                    b.Property<int>("StatusCheckThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("status_check_threshold_days");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_response_policies");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_response_policies_account_id");

                    b.ToTable("keep_response_policies", (string)null);
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepSetupDeferral", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("ClearedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("DeferredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deferred_at_utc");

                    b.Property<Guid>("DeferredByAccountUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deferred_by_account_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<Guid?>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<int>("Step")
                        .HasColumnType("integer")
                        .HasColumnName("step");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_keep_setup_deferrals");

                    b.HasIndex("AccountId", "Step")
                        .IsUnique()
                        .HasDatabaseName("ix_keep_setup_deferrals_account_step");

                    b.ToTable("keep_setup_deferrals", (string)null);
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.Account", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("PrimaryOwnerAccountUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_account_users_primary_owner_account_user_id");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountAuthCode", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_account_auth_codes_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountEntitlements", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithOne()
                        .HasForeignKey("OpHalo.Foundation.Core.Entities.Accounts.AccountEntitlements", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_entitlements_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountSession", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_sessions_accounts_account_id");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_sessions_account_users_account_user_id");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_users_accounts_account_id");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_account_users_users_user_id");

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.AccountUserDevice", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "AccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_user_devices_account_users_account_id_account_user_");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.MobileHandoffCode", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mobile_handoff_codes_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepBusinessProfile", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_business_profiles_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepCustomer", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_customers_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepProductOpsEvent", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_product_ops_events_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepPublicIntakeLink", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_public_intake_links_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepPublicIntakeSlugAlias", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_public_intake_slug_aliases_accounts_account_id");

                    b.HasOne("OpHalo.Keep.Core.Entities.KeepPublicIntakeLink", null)
                        .WithMany()
                        .HasForeignKey("IntakeLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_public_intake_slug_aliases_keep_public_intake_links_in");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepRequest", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_requests_accounts_account_id");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "AttentionClearedByAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_requests_account_users_account_id_attention_cleared_by");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "FeedbackReviewedByAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_requests_account_users_account_id_feedback_reviewed_by");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "FirstResponderAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_requests_account_users_account_id_first_responder_acco");

                    b.HasOne("OpHalo.Keep.Core.Entities.KeepCustomer", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "KeepCustomerId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_requests_keep_customers_account_id_keep_customer_id");

                    b.HasOne("OpHalo.Keep.Core.Entities.KeepRequestEvent", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "Id", "FirstResponseEventId")
                        .HasPrincipalKey("AccountId", "RequestId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_requests_first_response_event");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepRequestEvent", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "ActorAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_request_events_account_users_account_id_actor_account_");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "ParticipationNotificationIntendedRecipientAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_request_events_account_users_account_id_participation_");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "ParticipationPreviousResponsibleAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_request_events_account_users_account_id_participation_1");

                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "ParticipationTargetAccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keep_request_events_account_users_account_id_participation_2");

                    b.HasOne("OpHalo.Keep.Core.Entities.KeepRequest", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "RequestId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_request_events_keep_requests_account_id_request_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepRequestParticipant", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.AccountUser", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "AccountUserId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_request_participants_account_users_account_id_account_");

                    b.HasOne("OpHalo.Keep.Core.Entities.KeepRequest", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "RequestId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_request_participants_keep_requests_account_id_request_");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepResponsePolicy", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_response_policies_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Keep.Core.Entities.KeepSetupDeferral", b =>
                {
                    b.HasOne("OpHalo.Foundation.Core.Entities.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keep_setup_deferrals_accounts_account_id");
                });

            modelBuilder.Entity("OpHalo.Foundation.Core.Entities.Accounts.Account", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
