// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OpHalo.Foundation.Infrastructure.Persistence;

#nullable disable

namespace OpHalo.Foundation.Infrastructure.Migrations;

[DbContext(typeof(OpHaloDbContext))]
[Migration("20260816093000_RemovedProposedScopeLineSnapshotCleanupIndex")]
partial class RemovedProposedScopeLineSnapshotCleanupIndex
{
}
